version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evaluation-events-app
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: evaluation-events-mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - app-network
    command: ["--auth"]

networks:
  app-network:
    driver: bridge
