version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evaluation-events-app
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./src:/usr/src/app/src
      - ./server.js:/usr/src/app/server.js
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: evaluation-events-mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"
    command: ["--auth"]

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
